class Student

  # Remember, you can access your database connection anywhere in this class
  #  with DB[:conn]

  attr_accessor :name, :grade
  attr_reader :id

  def initialize(name = nil, grade = nil, id = nil)
    @name = name
    @grade = grade
    @id = id
  end

  # Create a students table
  def self.create_table
    sql_create = <<-SQL
      CREATE TABLE IF NOT EXISTS students (
        id INTEGER PRIMARY KEY,
        name TEXT,
        grade INTEGER
      )
    SQL
    DB[:conn].execute(sql_create)
  end

  # Remove the students table from the database
  def self.drop_table
    sql_drop = "DROP TABLE students"
    DB[:conn].execute(sql_drop)
  end

  # Save a student to the database
  def save
    sql_insert = <<-SQL
    INSERT INTO students (name, grade)
    VALUES(?, ?)
    SQL
    DB[:conn].execute(sql_insert, self.name, self.grade)
    # update the ID of the student now that it is generated by the database
    @id = DB[:conn].execute("SELECT last_insert_rowid() FROM students")[0][0]
  end

  # Create a student by instantiating and saving
  def self.create(attributes)
    student = Student.new()
    attributes.each {|key, value| student.send("#{key}=", value)}
    student.save
    student
  end

end
